# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b670b1fde3440e4668cf77367f83cf525cfefbb98b0fdff268eff5edfe6355b90cdee98b935f2ee1715bc0e5ce8edb370d27806bdbbbd208bdbfb6291365fbfd

test:
  secret_key_base: cd8478dda6e5016b222d83dc481ab597154630239c2c853736e064503964b0d3c9b76583fa8ecaf7a59867c8d9d86b840792105d0d6a7c1b41e42c30e093364c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
